// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gmgmabynzaqlvpbvfiem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdtZ21hYnluemFxbHZwYnZmaWVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMTI1NDAsImV4cCI6MjA3MTY4ODU0MH0.s5ilZlutBC56l9gGY13v0O_XcV3YQFaU8bW3gWxDH_U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});